export const Gents ={
    title:"Gents Fashion",
    image1:"shop/men/img1.avif",
    image2:"shop/men/im2.avif",
    image3:"shop/men/im3.avif",
    image4:"shop/men/im4.avif",
    image5:"shop/men/im5.avif",
    image6:"shop/men/im6.avif",
    image7:"shop/men/iim7.avif",
    image8:"shop/men/im8.avif",
    price1:" 6200 INR",
    price2:" 540 INR",
    price3:" 980 INR",
    price4:" 290 INR",
    price5:" 360 INR",
    price6:" 120 INR",
    price7:" 2902 INR",
    price8:" 390 INR",
}
export const Ladies ={
    title:"Ladies Fashion",
    image1:"shop/women/im1.avif",
    image2:"shop/women/im2.avif",
    image3:"shop/women/im3.avif",
    image4:"shop/women/im4.avif",
    image5:"shop/women/im5.avif",
    image6:"shop/women/im6.avif",
    image7:"shop/women/im7.avif",
    image8:"shop/women/im8.avif",
    image9:"shop/women/im9.avif",
    price1:" 6200 INR",
    price2:" 540 INR",
    price3:" 980 INR",
    price4:" 290 INR",
    price5:" 360 INR",
    price6:" 120 INR",
    price7:" 2902 INR",
    price8:" 390 INR",
    price9:" 890 INR",
}